version: "3.3"

services:
  simplefrontend:
    container_name: SimpleFrontend
    build:
      context: simplefrontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment: 
      REACT_APP_APIURL: simplebackend_spring:8080/
    depends_on:
      - simplebackend_spring
    networks:
      - frontnet
    stdin_open: true

  simplebackend_spring:
    container_name: simplebackend_spring
    build:
      context: simplebackend_spring
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/simpleapp
      SPRING_DATASOURCE_USERNAME: simpleapp
      SPRING_DATASOURCE_PASSWORD: simpleapp
    depends_on:
      - db
    networks:
      - frontnet
      - backnet

  db:
    container_name: mysql-db
    image: mysql:5.7
    ports:
      - 3306:3006
    environment:
      MYSQL_DATABASE: simpleapp
      MYSQL_USER: simpleapp
      MYSQL_PASSWORD: simpleapp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - backnet
  
  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - 8081:80
  #   networks:
  #     - backnet

volumes:
  mysql-data:

networks:
  frontnet:
  backnet:
