apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend:0.0.2
        imagePullPolicy: Never
        name: frontend
        ports:
        - containerPort: 80
          name: frontend
        env:
          - name: APIURL
            value: http://kubernetes.docker.internal:30003
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: frontend
