apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      #extension says there is an error, but there is not!
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: sefose/simpleapp-frontend:0.0.1
        imagePullPolicy: IfNotPresent
        name: frontend
        ports:
        - containerPort: 80
          name: frontend
        env:
          - name: APIURL
            value: http://cln01:30003
        resources:
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: frontend
