apiVersion: v1
kind: Service
metadata:
  name: simpleapp-mysql
  labels:
    app: simpleapp
spec:
  ports:
    - port: 3306
  selector:
    app: simpleapp
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: simpleapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: managed-nfs-storage
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: simpleapp-mysql
  labels:
    app: simpleapp
spec:
  selector:
    matchLabels:
      app: simpleapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: simpleapp
        tier: mysql
    spec:
      # securityContext:
      #   runAsUser: 0
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: simpleapp
        - name: MYSQL_USER
          value: simpleapp
        - name: MYSQL_PASSWORD
          value: simpleapp
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
