mysql:
  enabled: true
  image:
    repository: mysql
    tag: 5.6
  auth:
    rootPassword: root
    datebase: simpleapp
    username: simpleapp
    password: simpleapp

phpmyadmin:
  enabled: true
  service:
    type: NodePort
    nodePorts: 
      http: 30005